table fact_compensation
	lineageTag: 8c6df3bd-f868-4711-af77-43c4666d1f9e

	column CompensationID
		dataType: string
		lineageTag: 7b32e246-18ca-4693-8e1b-ac9c982cbae3
		summarizeBy: none
		sourceColumn: CompensationID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column EmployeeID
		dataType: string
		lineageTag: d5b978f6-4f06-40ff-bcb7-3250d7e08334
		summarizeBy: none
		sourceColumn: EmployeeID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column EffectiveDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3de01574-d29f-4fd5-b828-4a301f799123
		summarizeBy: none
		sourceColumn: EffectiveDate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Country
		dataType: string
		lineageTag: fdad3e3f-0815-4947-855f-c9f180ea9149
		summarizeBy: none
		sourceColumn: Country

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Currency
		dataType: string
		lineageTag: 2228ad5f-4f42-4b74-9feb-296630e52971
		summarizeBy: none
		sourceColumn: Currency

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PayGrade
		dataType: string
		lineageTag: 7be0295e-12d3-4b08-91b6-2e44c4c6c518
		summarizeBy: none
		sourceColumn: PayGrade

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column BaseSalary
		dataType: int64
		formatString: 0
		lineageTag: f47a181d-747e-4fb3-bf30-657fe0976215
		summarizeBy: sum
		sourceColumn: BaseSalary

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column BonusAmount
		dataType: double
		lineageTag: 3e4782bb-ed3b-4b20-a8b1-0be3791a51ad
		summarizeBy: sum
		sourceColumn: BonusAmount

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TotalCompensation
		dataType: double
		lineageTag: b16e253f-5ef4-405e-933a-41cdbe11b47a
		summarizeBy: sum
		sourceColumn: TotalCompensation

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CompensationChangeType
		dataType: string
		lineageTag: 628c39e8-65dd-4b5f-81ff-b2b30fce304b
		summarizeBy: none
		sourceColumn: CompensationChangeType

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition fact_compensation = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\Data Science Study materials and projects\Powerbi\Enterprise Workforce Intelligence & Attrition Analytics\Enterprise-Workforce-Intelligence\data\raw\fact_compensation.csv"),[Delimiter=",", Columns=10, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"CompensationID", type text}, {"EmployeeID", type text}, {"EffectiveDate", type date}, {"Country", type text}, {"Currency", type text}, {"PayGrade", type text}, {"BaseSalary", Int64.Type}, {"BonusAmount", type number}, {"TotalCompensation", type number}, {"CompensationChangeType", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

